openapi: 3.0.0
info:
  title: Recursive definition spec
  version: 1.0.0


paths:
  /:
    parameters:
      - required: false
        in: query
        name: generateError
        description: Generates an error if set to true
        example: true
    get:
      description: Retrieve all apps.
      summary: Retrieve all applications
      operationId: retrieveApplicationCollection
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

components:
  schemas:
    ProblemDetails:
      description: >
        Problem Details object as defined in
        [RFC7807](https://tools.ietf.org/html/rfc7807).
      type: object
      properties:
        type:
          type: string
          description: >
            A URI reference [RFC3986](https://tools.ietf.org/html/rfc3986) that
            identifies the problem type.  This specification encourages that,
            when dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML
            [W3C.REC-html5-20141028](https://tools.ietf.org/html/rfc7807#ref-W3C.REC-html5-20141028)).
        status:
          type: integer
          description: >
            The HTTP status code [RFC7231, Section
            6](https://tools.ietf.org/html/rfc7231#section-6) generated by the
            origin server for this occurrence of the problem. MUST match the
            HTTP status code.
          example: 400
        title:
          type: string
          description: >
            A short, human-readable summary of the problem type. This field
            SHOULD be the same as the recommended HTTP status phrase for that
            code (e.g., "Not Found" for 404, and so on).
          example: Bad Request
        detail:
          type: string
          description: >
            A human-readable explanation specific to this occurrence of the
            problem.
          example: Request is missing required parameter "foo".
        instance:
          type: string
          description: >
            A URI reference that identifies the specific occurrence of the
            problem.  It may or may not yield further information if
            dereferenced.
        errorId:
          type: string
          format: uuid
          description: >
            A unique ID for this error type
        childError:
          $ref: "#/components/schemas/ProblemDetails"
      required:
        - type
        - title
